---
title: "R Day 2"
author: "Sharon"
date: "9/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
gapminder <- read.csv(here::here("data", "gapminder5.csv"))
```

## Converting factors to characters
```{r}
str(gapminder)
gapminder$country <- as.character(gapminder$country)
gapminder$continent <- as.character(gapminder$continent)
str(gapminder)
```

## Natural log of GDP per capital and of population
```{r}
obs <- 1:nrow(gapminder)
for (i in obs){
  gapminder[i, "log_gdpPercap"] <- log(gapminder[i,"gdpPercap"])
  gapminder[i, "log_pop"] <- log(gapminder[i,"pop"])
}
head(gapminder)
```

## Mean life expectancy by continents
```{r}
continents <- unique(gapminder$continent)
for (i in continents){
  mean_le <- mean(gapminder$lifeExp[gapminder$continent==i], na.rm=TRUE)
  print(paste0(i, ":", mean_le))
}
```

## Mean life expectancy by year and continent
```{r}
years <- unique(gapminder$year)
for (i in continents){
  for (j in years){
    mean_le <- mean(gapminder$lifeExp[gapminder$continent==i&gapminder$year==j], na.rm=TRUE)
    print(paste0(i, j, ": ", mean_le))
  }
}
```

## SD of life expectancy by year and continent
```{r}
for (i in continents){
  for (j in years){
    sd_le <- sd(gapminder$lifeExp[gapminder$continent==i&gapminder$year==j], na.rm=TRUE)
    print(paste0(i, j, ": ", sd_le))
  }
}
```

## SD of life expectancy by year
```{r}
i <- 1987
while (i <= 2002){
  sd_le <- sd(gapminder$lifeExp[gapminder$year==i], na.rm=TRUE)
  print(paste0(i, ": ", sd_le))
  i <- i + 5
}
```

## Mean pop for year >= 1987
```{r}
for (i in years){
  if (i < 1987){
    print('year is less than 1987')
  }else{
    mean_pop <- mean(gapminder$pop[gapminder$year==i])
    print(paste0(i, ": ", mean_pop))
  }
}
```

## life expectancy function
```{r}
continent_le <-
  function(df, variable, continents){
    var <- df[[variable]][df$continent==continents]
    mean_le <- mean(var)
    median_le <- median(var)
    min_le <- min(var)
    max_le <- max(var)
    print(paste0('mean for ', continents, ": ", mean_le))
    print(paste0('median for ', continents, ": ", median_le))
    print(paste0('min for ', continents, ": ", min_le))
    print(paste0('max for ', continents, ": ", max_le))
  }

continent_le(gapminder, 'lifeExp', 'Europe')

```
